version: 2.1

jobs:
  publish:
    docker:
      - image: cimg/openjdk:11.0-browsers
    steps:
      - checkout
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish
  circle-all:
    docker:
    - image: busybox:1.34.1
    resource_class: small
    steps:
    - run:
        command: echo "All required jobs finished successfully"

workflows:
  tagged-build:
    jobs:
      - publish:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - circle-all:
          requires: []
          filters:
            tags:
              only: /.*/
